### ISSUE TITLE
Erick

### ISSUE THREAD

**Issue by ECely197** [carlos2barragan/Api_ecomerce#5]
product

name
description
price
stock
category
images
isActive

**Comment by Erickferpinedo** [comment]
bro como estas? esto ya esta incluido en todo el proyecto createAt
updateAt no hay que ponerlo asi por que tenemos el timestamps que eso lo genera mongo solo

**Comment by Erickferpinedo** [comment]
bro el is active para eso es el stock 
para saber la cantidad que hay disponible de cada producto o para que sirve?

**Comment by Erickferpinedo** [comment]
done
